### ISSUE TITLE
Output is reversed when using the trace file option

### ISSUE THREAD

**Issue by clubby789** [wapiflapi/villoc#17]
When using `setarch x86_64 -R ltrace -o trace ./target; villoc.py trace out.html`, the output is reversed. For exmple, the first `malloc` is at the bottom, and I have to read from bottom to top.

**Comment by wapiflapi** [comment]
That's intended. Usually I'm more interested in what happens last so it
shows first. That way when working on something I don't have to
repeatedly scroll all the way down to see what's going on and I can just
have the page auto-refresh.

If you want to change this it should be as easy as adding an option to
`argparse.ArgumentParser` (say `--chronological`) storing `reversed` or
`lambda x: x` in a `order` attribute, and then use it on this line
https://github.com/wapiflapi/villoc/blob/2647761f24c4cc854b88a899b836fd8949620912/villoc.py#L530
instead of always using `reversed`

PRs welcom ! Thank you for the feedback :-)

**Comment by wapiflapi** [comment]
That's intended. Usually I'm more interested in what happens last so it shows first. That way when working on something I don't have to repeatedly scroll all the way down to see what's going on and I can just have the page auto-refresh.

If you want to change this it should be as easy as adding an option to `argparse.ArgumentParser` (say `--chronological`) storing `reversed` or `lambda x: x` in a `order` attribute, and then use it on this line https://github.com/wapiflapi/villoc/blob/2647761f24c4cc854b88a899b836fd8949620912/villoc.py#L530 instead of always using `reversed`

PRs welcome ! Thank you for the feedback :-)

**Comment by wapiflapi** [comment]
Thanks for the contribution :-)
